[package]
name = "special-friends"
version = "1.0.1"
authors = ["KunoiSayami <46131041+KunoiSayami@users.noreply.github.com>"]
edition = "2018"

[dependencies]
grammers-client = { git = "https://github.com/Lonami/grammers" }
grammers-session = { git = "https://github.com/Lonami/grammers" }
tokio = { version = "1", features = ["full"] }
simple_logger = "1.11.0"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }
serde_derive = "1.0.123"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
grammers-tl-gen = { git = "https://github.com/Lonami/grammers" }
grammers-tl-types = { git = "https://github.com/Lonami/grammers" }
reqwest = { version = "0.11", features = ["socks", "serde_json", "json"] }

[target.aarch64-unknown-linux-musl.dependencies]
openssl = { version = "0.10", features = ["vendored"] }
